name: Update portfolio-1 data

on:
  schedule:
    - cron: '25 14 * * 1-5'  # 每周一到周五的UTC时间14:25（东八区时间22:25）执行

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run portfolio-1.py
        run: python portfolio-1.py
        working-directory: my-investment/portfolio
        env:
          FEISHU_WEBHOOK_URL: ${{ secrets.FEISHU_WEBHOOK_URL }}

      - name: Commit and push if it changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          if git diff --quiet HEAD; then
            echo "No changes to commit"
          else
            git commit -m "Update data"
            git push
          fi
      
      - name: Sync data to gh-pages
        run: |
          git checkout gh-pages
          git checkout main -- my-investment/data
          git commit -m "Sync data to gh-pages"
          git push origin gh-pages
